---
title: "Cancer research explorer - China vs US"
author: "Sergio Valbuena"
date: "2025-10-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
if(!require("showtext")) install.packages("showtext")

library(tidyr)
library(dplyr)
library(ggplot2)
library(showtext)
library(patchwork)

font_add("Calibri", "C:/Windows/Fonts/calibri.ttf")  # path for Windows
showtext_auto()
```


```{r}
proj_dir <- file.path("C:", "Users", "svalb", "OneDrive", "Documentos", "GitHub", "cancer_studies_deployment", "public", "data")
out_dir <- file.path("C:", "Users", "svalb", "OneDrive", "Documentos", "GitHub", "articles_cancer_research_explorer")
```

```{r}
df <- read.csv(file.path(proj_dir, "articles_country_year_cancer_lite.csv"))

top5_cancers <- df %>% group_by(Cancer) %>% summarise(articles_cancer = sum(Articles))
top5_cancers <- (top5_cancers[order(top5_cancers$articles_cancer, decreasing = TRUE),] %>% filter(!Cancer %in% c("Undetermined cancer", "Other cancer")))[1:5,]

df_lite <- df %>% filter(Country %in% c("China", "United States"))
df_lite <- df_lite %>% filter(Cancer %in% top5_cancers$Cancer)
```



```{r}
df_stats <- df_lite %>% pivot_wider(names_from = Cancer, values_from = Articles)

df_stats$Mean <- rowMeans(df_stats[unique(df_lite$Cancer)])
```



```{r, warning=FALSE}
font_size = 18

p1 <- ggplot(df_stats, aes(x = Year, y = Mean, colour = Country))+
  geom_line(linewidth = 1.2)+
  geom_line(data = df_lite %>% filter(Country == "United States"), aes(x=Year, y=Articles, group = Cancer), linewidth = 0.55, linetype = "dashed")+
  geom_line(data = df_lite %>% filter(Country == "China"), aes(x=Year, y=Articles, group = Cancer), linewidth = 0.55, linetype = "dashed")+
  scale_y_continuous(expand = c(0,0))+
  scale_x_continuous(limits = c(1990, 2024), breaks = seq(1990, 2024, 2), expand = c(0,0))+
  scale_color_manual(values = c("China" = "#A000C2",
                                "United States" = "#166128"))+
  theme_minimal(base_family = "Calibri")+
  ylab("Studies")+
  labs(title = "Evolution of research about top 5 studied cancers in United States and China")+
  theme(
    plot.background = element_rect(fill = '#f6f8fa'),
    text = element_text(family = "Calibri", size = font_size+3),
    axis.title = element_text(size = font_size + 4),
    axis.text.x = element_text(angle = 90),
    plot.title = element_text(size = font_size + 16, family = "Calibri", hjust = 0.5),
    legend.position = "inside",
    legend.position.inside = c(0.65, 0.7),
    legend.title = element_blank(),
    legend.text = element_text(size = font_size + 1)
  )

p1
```






```{r}
df_full <- read.csv(file.path(proj_dir, "articles_country_year_cancer.csv"))

df_full_lite <- df_full %>% filter(Cancer %in% top5_cancers$Cancer)
```


```{r}
df_compiled_disc <- data.frame(matrix(nrow = 3, ncol = 0))

df_compiled_disc$Country <- factor(x=c("China", "United States", "Others"),
                                   levels = rev(c("China", "United States", "Others")))
rownames(df_compiled_disc) <- df_compiled_disc$Country
df_compiled_disc$Y1990 <- NA
df_compiled_disc$Y2024 <- NA


df_compiled_disc["China", "Y1990"] <- sum((df_full_lite %>% filter(Year == 1990 & Country == "China"))$Articles)
df_compiled_disc["United States", "Y1990"] <- sum((df_full_lite %>% filter(Year == 1990 & Country == "United States"))$Articles)
df_compiled_disc["Others", "Y1990"] <- sum((df_full_lite %>% filter(Year == 1990 & !Country %in% c("China", "United States")))$Articles)

df_compiled_disc["China", "Y2024"] <- sum((df_full_lite %>% filter(Year == 2024 & Country == "China"))$Articles)
df_compiled_disc["United States", "Y2024"] <- sum((df_full_lite %>% filter(Year == 2024 & Country == "United States"))$Articles)
df_compiled_disc["Others", "Y2024"] <- sum((df_full_lite %>% filter(Year == 2024 & !Country %in% c("China", "United States")))$Articles)


sum_1990 <- sum(df_compiled_disc$Y1990)
sum_2024 <- sum(df_compiled_disc$Y2024)

df_compiled_disc["China", "Y1990"] <- df_compiled_disc["China", "Y1990"] / sum_1990 * 100
df_compiled_disc["United States", "Y1990"] <- df_compiled_disc["United States", "Y1990"] / sum_1990 * 100
df_compiled_disc["Others", "Y1990"] <- df_compiled_disc["Others", "Y1990"] / sum_1990 * 100

df_compiled_disc["China", "Y2024"] <- df_compiled_disc["China", "Y2024"] / sum_2024 * 100
df_compiled_disc["United States", "Y2024"] <- df_compiled_disc["United States", "Y2024"] / sum_2024 * 100
df_compiled_disc["Others", "Y2024"] <- df_compiled_disc["Others", "Y2024"] / sum_2024 * 100

# Position of labels
df_compiled_disc$ymax_1990 <- cumsum(df_compiled_disc$Y1990)
df_compiled_disc$ymin_1990 <- c(0, head(df_compiled_disc$ymax_1990, n=-1))
df_compiled_disc$label_position_1990 <- (df_compiled_disc$ymax_1990+df_compiled_disc$ymin_1990)/2

df_compiled_disc$ymax_2024 <- cumsum(df_compiled_disc$Y2024)
df_compiled_disc$ymin_2024 <- c(0, head(df_compiled_disc$ymax_2024, n=-1))
df_compiled_disc$label_position_2024 <- (df_compiled_disc$ymax_2024+df_compiled_disc$ymin_2024)/2

df_compiled_disc$Y1990 <- round(df_compiled_disc$Y1990, 2)
df_compiled_disc$Y1990_text <- paste0(as.character(df_compiled_disc$Y1990), "%")

df_compiled_disc$Y2024 <- round(df_compiled_disc$Y2024, 2)
df_compiled_disc$Y2024_text <-  paste0(df_compiled_disc$Y2024, "%")

df_compiled_disc <- df_compiled_disc[,c("Country", "Y1990", "Y2024", "Y1990_text", "Y2024_text", "label_position_1990", "label_position_2024")]
```





```{r}
pie1990 <- ggplot(df_compiled_disc, aes(x="", y=Y1990, fill=Country))+
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0)+
  geom_text(data = subset(df_compiled_disc, Country == "China"), aes(x=1.9, y=label_position_1990, label=Y1990_text), inherit.aes = FALSE, hjust=0.5, vjust=1, family = "Calibri", size = font_size-11)+
  geom_text(data = subset(df_compiled_disc, Country == "United States"), aes(x=2, y=label_position_1990, label=Y1990_text), inherit.aes = FALSE, hjust=0.5, vjust=1, family = "Calibri", size = font_size-10)+
  scale_fill_manual(breaks = c("China", "United States"),
                   values = c("China" = "#A000C2",
                                "United States" = "#166128",
                                "Others" = "lightgrey"))+
  labs(title = "1990")+
  theme_minimal(base_family = "Calibri")+
  theme(
    plot.background = element_rect(fill = NA, linewidth = NA),
    text=element_blank(),
    plot.title = element_text(family = "Calibri", size = font_size + 7, hjust = 0.5, margin = margin(t = 20, r = 0, b = 0, l = 0)),
    panel.grid = element_blank(),
    legend.position = "none"
  )

pie1990
```




```{r}
pie2024 <- ggplot(df_compiled_disc, aes(x="", y=Y2024, fill=Country))+
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0)+
  geom_text(data = subset(df_compiled_disc, Country == "China"), aes(x=2, y=label_position_2024, label=Y2024_text), inherit.aes = FALSE, hjust=0.5, vjust=1, family = "Calibri", size = font_size-11)+
  geom_text(data = subset(df_compiled_disc, Country == "United States"), aes(x=1.8, y=label_position_2024, label=Y2024_text), inherit.aes = FALSE, hjust=0.5, vjust=1, family = "Calibri", size = font_size-10)+
  scale_fill_manual(breaks = c("China", "United States"),
                   values = c("China" = "#A000C2",
                                "United States" = "#166128",
                                "Others" = "lightgrey"))+
  labs(title = "2024")+
  theme_minimal(base_family = "Calibri")+
  theme(
    plot.background = element_rect(fill = NA, linewidth = NA),
    text=element_blank(),
    plot.title = element_text(family = "Calibri", size = font_size + 7, hjust = 0.5, margin = margin(t = 20, r = 0, b = 0, l = 0)),
    panel.grid = element_blank(),
    legend.position = "none"
  )

pie2024
```





```{r, warning=F}
width_out = 1920
height_out = 1080

transparent_spacer <- plot_spacer() + 
  theme(
    panel.background = element_rect(fill = NA, color = NA),
    plot.background  = element_rect(fill = NA, color = NA)
  )


pies <-  pie1990 +  pie2024 

full_plot <- p1 + inset_element(pies, left = -0.05, bottom = 0.4, right = 0.5, top = 1.1) & theme(plot.background = element_rect(linewidth = NA))

full_plot 

ggsave(plot = full_plot, filename = file.path(out_dir, "evolution_lines_pies.jpg"), device = "jpg", width = width_out, height = height_out, units = "px")
```


































